[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E9", "F63", "F7", "F82"]

[tool.pytest.ini_options]
testpaths = ["src/tests"]
norecursedirs = ["data", ".git", ".venv", ".mypy_cache", ".pytest_cache"]
